export const products = {
    category: [
        {
            category: 'T-Shart',
            data: [
                {
                    name: 't-shirt 1',
                    product_id: 1,
                    price: 300,
                    image: require('./Fashion/t-shart1.jpg'),
                    quantity: 1,
                },
                {
                    name: 't-shirt 2',
                    product_id: 2,
                    price: 350,
                    image: require('./Fashion/t-shart2.jpg'),
                    quantity: 1,
                },
                {
                    name: 't-shirt 3',
                    price: 450,
                    product_id: 3,
                    image: require('./Fashion/t-shart3.jpg'),
                    quantity: 1,
                },
                {
                    name: 't-shirt 4',
                    price: 200,
                    product_id: 4,
                    image: require('./Fashion/t-shart4.jpg'),
                    quantity: 1,
                },
                {
                    name: 't-shirt 5',
                    price: 300,
                    product_id: 5,
                    image: require('./Fashion/t-shart5.jpg'),
                    quantity: 1,
                },
            ],
        },
        {
            category: 'Jeans',
            data: [
                {
                    name: 'jeans-1',
                    price: 700,
                    product_id:6,
                    image: require('./Fashion/jeans1.jpg'),
                    quantity: 1,
                },
                {
                    name: 'jeans-2',
                    product_id: 7,
                    price: 650,
                    image: require('./Fashion/jeans2.jpg'),
                    quantity: 1,
                },
                {
                    name: 'jeans-3',
                    product_id: 8,
                    price: 800,
                    image: require('./Fashion/jeans3.jpg'),
                    quantity: 1,
                },
                {
                    name: 'jeans-4',
                    product_id: 9,
                    price: 650,
                    image: require('./Fashion/jeans4.jpg'),
                    quantity: 1,
                },
                {
                    name: 'jeans-5',
                    product_id: 10,
                    price: 500,
                    image: require('./Fashion/jeans5.jpg'),
                    quantity: 1,
                },
            ],
        },
        {
            category: 'Shoes',
            data: [
                {
                    name: 'Shoes-1',
                    product_id: 11,
                    price: 200,
                    image: require('./Fashion/Shoes1.jpg'),
                    quantity: 1,
                },
                {
                    name: 'Shoes-2',
                    product_id: 12,
                    price: 250,
                    image: require('./Fashion/Shoes2.jpg'),
                    quantity: 1,
                },
                {
                    name: 'Shoes-3',
                    product_id: 13,
                    price: 300,
                    image: require('./Fashion/Shoes3.jpg'),
                    quantity: 1,
                },
                {
                    name: 'Shoes-4',
                    product_id: 14,
                    price: 250,
                    image: require('./Fashion/Shoes4.jpg'),
                    quantity: 1,
                },
                {
                    name: 'Shoes-5',
                    product_id: 15,
                    price: 200,
                    image: require('./Fashion/Shoes5.jpg'),
                    quantity: 1,
                },
            ],
        },
        {
            category: 'Jacket',
            data: [
                {
                    name: 'jacket-1',
                    product_id: 16,
                    price: 900,
                    image: require('./Fashion/jacket1.jpg'),
                    quantity: 1,
                },
                {
                    name: 'jacket-2',
                    product_id: 17,
                    price: 850,
                    image: require('./Fashion/jacket2.jpg'),
                    quantity: 1,
                },
                {
                    name: 'jacket-3',
                    product_id: 18,
                    price: 850,
                    image: require('./Fashion/jacket3.jpg'),
                    quantity: 1,
                },
                {
                    name: 'jacket-4',
                    product_id: 19,
                    price: 950,
                    image: require('./Fashion/jacket4.jpg'),
                    quantity: 1,
                },
                {
                    name: 'jacket-5',
                    product_id: 20,
                    price: 900,
                    image: require('./Fashion/jacket5.jpg'),
                    quantity: 1,
                },
            ],
        },
        {
            category: 'Slipper',
            data: [
                {
                    name: 'slipper-1',
                    product_id: 21,
                    price: 200,
                    image: require('./Fashion/Slipper1.jpg'),
                    quantity: 1,
                },
                {
                    name: 'slipper-2',
                    product_id: 22,
                    price: 250,
                    image: require('./Fashion/Slipper2.jpg'),
                    quantity: 1,
                },
                {
                    name: 'slipper-3',
                    product_id: 23,
                    price: 300,
                    image: require('./Fashion/Slipper3.jpg'),
                    quantity: 1,
                },
                {
                    name: 'slipper-4',
                    product_id: 24,
                    price: 250,
                    image: require('./Fashion/Slipper4.jpg'),
                    quantity: 1,
                },
                {
                    name: 'slipper-5',
                    product_id: 25,
                    price: 200,
                    image: require('./Fashion/Slipper5.jpg'),
                    quantity: 1,
                },
            ],
        },
        {
            category: 'Trousers',
            data: [
                {
                    name: 'Trousers-1',
                    product_id: 26,
                    price: 200,
                    image: require('./Fashion/Trousers1.jpg'),
                    quantity: 1,
                },
                {
                    name: 'Trousers-2',
                    product_id: 27,
                    price: 250,
                    image: require('./Fashion/Trousers2.jpg'),
                    quantity: 1,
                },
                {
                    name: 'Trousers-3',
                    product_id: 28,
                    price: 300,
                    image: require('./Fashion/Trousers3.jpg'),
                    quantity: 1,
                },
                {
                    name: 'Trousers-4',
                    product_id: 29,
                    price: 250,
                    image: require('./Fashion/Trousers4.jpg'),
                    quantity: 1,
                },
                {
                    name: 'Trousers-5',
                    product_id: 30,
                    price: 200,
                    image: require('./Fashion/Trousers5.jpg'),
                    quantity: 1,
                },
            ],
        },
    ],
};
